# Use an official Python runtime as a parent image
FROM python:3.11-slim

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy the entire project to the working directory
COPY . .

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Make the run script executable
COPY run.sh /usr/src/app/run.sh
RUN chmod +x /usr/src/app/run.sh

# Run startup.sh to set up the environment
RUN chmod +x ./startup.sh && ./startup.sh

# Set the entrypoint for the container
ENTRYPOINT ["/usr/src/app/run.sh"]
